<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <DefineConstants>TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicData" Version="6.16.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.6" />
    <PackageReference Include="Sharpnado.Tabs" Version="2.0.1" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1687" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />  
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blastic.Data\Blastic.Data.csproj" />
    <ProjectReference Include="..\Blastic.Forms\Blastic.Forms.csproj" />
    <ProjectReference Include="..\Blastic\Blastic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\SearchView.xaml.cs">
      <DependentUpon>SearchView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\LibraryView.xaml.cs">
      <DependentUpon>LibraryView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\HomeView.xaml.cs">
      <DependentUpon>HomeView.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="UserInterface\HomeView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="UserInterface\MainView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>