<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
    <PackageReference Include="AiForms.SettingsView" Version="1.3.5" />
    <PackageReference Include="DynamicData" Version="6.16.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.6" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.1709-pre4" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />  
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blastic.Data\Blastic.Data.csproj" />
    <ProjectReference Include="..\Blastic.Forms\Blastic.Forms.csproj" />
    <ProjectReference Include="..\Blastic\Blastic.csproj" />
    <ProjectReference Include="..\Blastic.CodeGeneration\Blastic.CodeGeneration.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="Properties\Resources.resx" />
		<AdditionalFiles Include="Properties\Resources.tr-tr.resx" />
	</ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\RatingBar.xaml.cs">
      <DependentUpon>RatingBar.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\ChapterDetailsOverlayView.xaml.cs">
      <DependentUpon>ChapterDetailsOverlayView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\BookView.xaml.cs">
      <DependentUpon>BookView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\HomeViewContent.xaml.cs">
      <DependentUpon>HomeViewContent.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\MediaPlayer\CollapsedView.xaml.cs">
      <DependentUpon>CollapsedView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\MediaPlayer\ExtendedView.xaml.cs">
      <DependentUpon>ExtendedView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\SearchViewContent.xaml.cs">
      <DependentUpon>SearchViewContent.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\Settings\SettingsViewContent.xaml.cs">
      <DependentUpon>SettingsViewContent.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\Settings\SettingsView.xaml.cs">
      <DependentUpon>SettingsView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\SearchView.xaml.cs">
      <DependentUpon>SearchView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\LibraryView.xaml.cs">
      <DependentUpon>LibraryView.xaml</DependentUpon>
    </Compile>
    <Compile Update="UserInterface\HomeView.xaml.cs">
      <DependentUpon>HomeView.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="UserInterface\HomeView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="UserInterface\MainView.xaml">
      <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>