<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="7.0.0" />
		<PackageReference Include="Xamarin.Forms" Version="5.0.0.2291" />
		<PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="7.0.0" />
		<PackageReference Include="System.Reactive" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Blastic\Blastic.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Controls\ChildWindow.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="Themes\Form.xaml.cs">
			<DependentUpon>Form.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\Colors.xaml.cs">
			<DependentUpon>Colors.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\ChildWindow.xaml.cs">
			<DependentUpon>ChildWindow.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\DynamicControls\PasswordEntry.xaml.cs">
			<DependentUpon>PasswordEntry.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\DynamicControls\Entry.xaml.cs">
			<DependentUpon>Entry.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\DynamicControls\Picker.xaml.cs">
			<DependentUpon>Picker.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\DynamicControls\CheckBox.xaml.cs">
			<DependentUpon>CheckBox.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\DynamicControls\Group.xaml.cs">
			<DependentUpon>Group.xaml</DependentUpon>
		</Compile>
		<Compile Update="Themes\DynamicControls\Label.xaml.cs">
			<DependentUpon>Label.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Themes\DynamicControl.xaml">
			<Generator>MSBuild:UpdateDesignTimeXaml</Generator>
		</EmbeddedResource>
	</ItemGroup>
</Project>
