<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="System.Text.Json" Version="5.0.0" />
	<PackageReference Include="Xamarin.Forms" Version="5.0.0.1709-pre4" />
	<PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.0" />
	<PackageReference Include="System.Reactive" Version="4.4.1" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Blastic.Data\Blastic.Data.csproj" />
	<ProjectReference Include="..\Blastic\Blastic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\ChildWindow.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Themes\Form.xaml.cs">
      <DependentUpon>Form.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\Colors.xaml.cs">
      <DependentUpon>Colors.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\ChildWindow.xaml.cs">
      <DependentUpon>ChildWindow.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\DynamicControls\PasswordEntry.xaml.cs">
      <DependentUpon>PasswordEntry.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\DynamicControls\Entry.xaml.cs">
      <DependentUpon>Entry.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\DynamicControls\Picker.xaml.cs">
      <DependentUpon>Picker.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\DynamicControls\CheckBox.xaml.cs">
      <DependentUpon>CheckBox.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\DynamicControls\Group.xaml.cs">
      <DependentUpon>Group.xaml</DependentUpon>
    </Compile>
    <Compile Update="Themes\DynamicControls\Label.xaml.cs">
      <DependentUpon>Label.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
	<EmbeddedResource Update="Themes\DynamicControl.xaml">
	  <Generator>MSBuild:UpdateDesignTimeXaml</Generator>
	</EmbeddedResource>
  </ItemGroup>
</Project>
