<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.2.4" />
    <PackageVersion Include="Avalonia.Skia" Version="11.2.4" />
    <PackageVersion Include="Avalonia.ReactiveUI" Version="11.2.4" />
    <PackageVersion Include="Bindables.Maui" Version="1.4.1" />
    <PackageVersion Include="Depso" Version="1.0.2" />
    <PackageVersion Include="Dragablz" Version="0.0.3.234" />
    <PackageVersion Include="DynamicData" Version="9.1.1" />
    <PackageVersion Include="InputSimulatorStandard" Version="1.0.0" />
    <PackageVersion Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.12.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="9.0.40" />
    <PackageVersion Include="NuGet.Build.Tasks.Pack" Version="6.13.1" />
    <PackageVersion Include="SharpVectors" Version="1.8.4.2" />
    <PackageVersion Include="SkiaSharp" Version="2.88.9" />
    <PackageVersion Include="SkiaSharp.Views.Maui.Controls" Version="2.88.9" />
    <PackageVersion Include="Svg.SourceGenerator.Skia" Version="2.0.0.4" />
    <PackageVersion Include="System.Collections.Immutable" Version="9.0.2" />
    <PackageVersion Include="System.Reactive" Version="6.0.1" />
    <PackageVersion Include="System.Text.Json" Version="9.0.2" />
  </ItemGroup>
</Project>