<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.2" />
    <PackageVersion Include="Avalonia.Skia" Version="12.1.2" />
    <PackageVersion Include="Avalonia.ReactiveUI" Version="11.3.8" />
    <PackageVersion Include="Bindables.Maui" Version="1.4.1" />
    <PackageVersion Include="Depso" Version="1.0.4" />
    <PackageVersion Include="Dragablz" Version="0.0.3.234" />
    <PackageVersion Include="DynamicData" Version="9.4.33" />
    <PackageVersion Include="InputSimulatorStandard" Version="1.0.0" />
    <PackageVersion Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="5.9.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="5.9.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Data.Sqlite.Core" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.101" />
    <PackageVersion Include="SharpVectors" Version="1.8.6" />
    <PackageVersion Include="Svg.Skia" Version="5.2.3" />
    <PackageVersion Include="SkiaSharp" Version="4.152.0" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <PackageVersion Include="SkiaSharp.Views.Maui.Controls" Version="4.152.0" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.12" />
    <PackageVersion Include="System.Reactive" Version="7.0.0" />
    <PackageVersion Include="System.Text.Json" Version="10.0.12" />
  </ItemGroup>
</Project>
