//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blastic.Forms.Sample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blastic.Forms.Sample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End frame.
        /// </summary>
        internal static string Sample_AddJob_EndFrame {
            get {
                return ResourceManager.GetString("Sample.AddJob.EndFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene name.
        /// </summary>
        internal static string Sample_AddJob_SceneName {
            get {
                return ResourceManager.GetString("Sample.AddJob.SceneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start frame.
        /// </summary>
        internal static string Sample_AddJob_StartFrame {
            get {
                return ResourceManager.GetString("Sample.AddJob.StartFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine already exists.
        /// </summary>
        internal static string Sample_AddMachine_AlreadyExists {
            get {
                return ResourceManager.GetString("Sample.AddMachine.AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine name.
        /// </summary>
        internal static string Sample_AddMachine_MachineName {
            get {
                return ResourceManager.GetString("Sample.AddMachine.MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds per frame.
        /// </summary>
        internal static string Sample_AddMachine_SecondsPerFrame {
            get {
                return ResourceManager.GetString("Sample.AddMachine.SecondsPerFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Sample_Cancel {
            get {
                return ResourceManager.GetString("Sample.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Sample_Create {
            get {
                return ResourceManager.GetString("Sample.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Machine.
        /// </summary>
        internal static string Sample_Home_AddMachine {
            get {
                return ResourceManager.GetString("Sample.Home.AddMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Sample_Home_Title {
            get {
                return ResourceManager.GetString("Sample.Home.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Job.
        /// </summary>
        internal static string Sample_Machines_AddJob {
            get {
                return ResourceManager.GetString("Sample.Machines.AddJob", resourceCulture);
            }
        }
    }
}
