<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>netcoreapp3.1</TargetFramework>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Blastic\Blastic.csproj" />
		<ProjectReference Include="..\Blastic.CodeGeneration\Blastic.CodeGeneration.csproj"
		                  OutputItemType="Analyzer"
		                  ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>