using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Blastic.CodeGeneration.CSharp;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Blastic.CodeGeneration;

[Generator]
public class ResxLocalizationSourceGenerator : IIncrementalGenerator
{
	private const string AttributeNamespace = "Blastic.CodeGeneration";
	private const string AttributeName = "ResxLocalizationSourceAttribute";
	private const string AttributeFullName = $"{AttributeNamespace}.{AttributeName}";

	private const string AttributeText = $$"""
		namespace {{AttributeNamespace}}
		{
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
			internal class {{AttributeName}} : global::System.Attribute
			{
				public {{AttributeName}}(string resourceEndsWith)
				{
				}
			}
		}
		""";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(i => i.AddSource(
			$"{AttributeName}.g.cs",
			AttributeText.Trim()));

		IncrementalValueProvider<ImmutableArray<AdditionalText>> additionalTexts = context.AdditionalTextsProvider
			.Where(x => x.Path.EndsWith(".resx", StringComparison.InvariantCultureIgnoreCase))
			.Where(x => x != null)
			.Collect();

		IncrementalValueProvider<ImmutableArray<ClassDeclarationSyntax>> classDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (x, _) => IsSyntaxTargetForGeneration(x),
				static (x, _) => GetSemanticTargetForGeneration(x))
			.Where(static x => x is not null)
			.Collect()!;

		context.RegisterSourceOutput(
			context.CompilationProvider.Combine(additionalTexts).Combine(classDeclarations),
			static (context, source) => Execute(context, source.Left.Left, source.Left.Right, source.Right));
	}

	private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
	{
		return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
	}

	private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
	{
		if (context.Node is not ClassDeclarationSyntax classSyntax)
		{
			return null;
		}

		INamedTypeSymbol? symbol = context.SemanticModel.GetDeclaredSymbol(classSyntax);

		if (symbol == null)
		{
			return null;
		}

		if (symbol.GetAttributes().Any(x => x.AttributeClass?.ToDisplayString() == AttributeFullName))
		{
			return classSyntax;
		}

		return null;
	}

	private static void Execute(
		SourceProductionContext context,
		Compilation compilation,
		ImmutableArray<AdditionalText> source,
		ImmutableArray<ClassDeclarationSyntax> classes)
	{
		if (classes.Length == 0)
		{
			return;
		}

		foreach (ClassDeclarationSyntax @class in classes)
		{
			INamedTypeSymbol? classSymbol = compilation
				.GetSemanticModel(@class.SyntaxTree)
				.GetDeclaredSymbol(@class);

			if (classSymbol == null)
			{
				continue;
			}

			List<string> resources = classSymbol
				.GetAttributes()
				.Where(x => x.AttributeClass?.ToDisplayString() == AttributeFullName)
				.SelectMany(x => x.ConstructorArguments.Select(y => y.Value as string))
				.Where(x => x != null)
				.ToList()!;

			List<LocalizedText> localizedTexts = source.GetLocalizedTexts(resources);

			CodeBuilder codeBuilder = new();

			codeBuilder.AppendLine("// <auto-generated/>");
			codeBuilder.AppendLine();

			codeBuilder.AppendLine("#nullable enable");
			codeBuilder.AppendLine();

			using (codeBuilder.AddNamespace(classSymbol))
			{
				using (ClassBuilder classBuilder = codeBuilder.AddClass(classSymbol))
				{
					classBuilder.AddBase("global::Blastic.Services.Localization.ILocalizationSource");

					codeBuilder.AppendLine("public global::Blastic.Ordering.Order Order { get; }");
					codeBuilder.AppendLine();

					foreach (string id in localizedTexts.Select(x => x.Id).Distinct())
					{
						codeBuilder.AppendLine($"public const string {id.ToPropertyName()} = @\"{id}\";");
					}

					codeBuilder.AppendLine();

					using (MethodBuilder method = codeBuilder.Method("string?", "GetValue"))
					{
						method.AddParameter("string", "key");
						method.AddParameter("global::System.Globalization.CultureInfo", "culture");

						codeBuilder.AppendLine("string cultureId = culture.Name.ToLowerInvariant();");
						codeBuilder.AppendLine();

						using (codeBuilder.Switch("key"))
						{
							foreach (IGrouping<string, LocalizedText> grouping in localizedTexts.GroupBy(x => x.Id))
							{
								string id = grouping.Key;

								foreach (LocalizedText localizedText in grouping.OrderByDescending(x => x.Culture.Length))
								{
									codeBuilder.Append($"case {id.ToPropertyName()}");

									if (localizedText.Culture != "")
									{
										codeBuilder.Append(" when cultureId == \"", indent: false);
										codeBuilder.Append(localizedText.Culture, indent: false);
										codeBuilder.Append("\"", indent: false);
									}

									codeBuilder.AppendLine(":", indent: false);

									codeBuilder.Indent();
									codeBuilder.AppendLine($"return @\"{localizedText.Text}\";");
									codeBuilder.Unindent();
								}
							}

							using (codeBuilder.Default())
							{
								codeBuilder.AppendLine("return null;");
							}
						}
					}
				}
			}

			context.AddSource(classSymbol.Name, codeBuilder.ToString());
		}
	}
}