using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Blastic.CodeGeneration.CSharp;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Blastic.CodeGeneration;

[Generator]
public class ResxLocalizablePropertiesGenerator : IIncrementalGenerator
{
	private const string LocalizationService = "global::Blastic.Services.Localization.ILocalizationService";
	private const string ReadOnlyReactiveProperty = "global::Blastic.Reactive.IReadOnlyReactiveProperty<string>";
	private const string LocalizableReactiveProperty = "global::Blastic.Reactive.LocalizableReactiveProperty";

	private const string AttributeNamespace = "Blastic.CodeGeneration";
	private const string AttributeName = "ResxLocalizablePropertiesAttribute";
	private const string AttributeFullName = $"{AttributeNamespace}.{AttributeName}";

	private const string AttributeText = $$"""
		namespace {{AttributeNamespace}}
		{
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true)]
			internal class {{AttributeName}} : global::System.Attribute
			{
				public {{AttributeName}}(string resourceEndsWith)
				{
				}
			}
		}
		""";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(i => i.AddSource(
			$"{AttributeName}.g.cs",
			AttributeText));

		IncrementalValueProvider<ImmutableArray<AdditionalText>> additionalTexts = context.AdditionalTextsProvider
			.Where(x => x.Path.EndsWith(".resx", StringComparison.InvariantCultureIgnoreCase))
			.Where(x => x != null)
			.Collect();

		IncrementalValueProvider<ImmutableArray<ClassDeclarationSyntax>> classDeclarations = context.SyntaxProvider
			.CreateSyntaxProvider(
				static (x, _) => IsSyntaxTargetForGeneration(x),
				static (x, _) => GetSemanticTargetForGeneration(x))
			.Where(static x => x is not null)
			.Collect()!;

		context.RegisterSourceOutput(
			context.CompilationProvider.Combine(additionalTexts).Combine(classDeclarations),
			static (context, source) => Execute(context, source.Left.Left, source.Left.Right, source.Right));
	}

	private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
	{
		return node is ClassDeclarationSyntax { AttributeLists.Count: > 0 };
	}

	private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
	{
		if (context.Node is not ClassDeclarationSyntax classSyntax)
		{
			return null;
		}

		INamedTypeSymbol? symbol = context.SemanticModel.GetDeclaredSymbol(classSyntax);

		if (symbol == null)
		{
			return null;
		}

		if (symbol.GetAttributes().Any(x => x.AttributeClass?.ToDisplayString() == AttributeFullName))
		{
			return classSyntax;
		}

		return null;
	}

	public static void Execute(
		SourceProductionContext context,
		Compilation compilation,
		ImmutableArray<AdditionalText> source,
		ImmutableArray<ClassDeclarationSyntax> classes)
	{
		if (classes.Length == 0)
		{
			return;
		}

		foreach (ClassDeclarationSyntax @class in classes)
		{
			INamedTypeSymbol? classSymbol = compilation
				.GetSemanticModel(@class.SyntaxTree)
				.GetDeclaredSymbol(@class);

			if (classSymbol == null)
			{
				continue;
			}

			List<string> resources = classSymbol
				.GetAttributes()
				.Where(x => x.AttributeClass?.ToDisplayString() == AttributeFullName)
				.SelectMany(x => x.ConstructorArguments.Select(y => y.Value as string))
				.Where(x => x != null)
				.ToList()!;

			List<LocalizedText> localizedTexts = source.GetLocalizedTexts(resources);
			Tree<string> tree = BuildTree(localizedTexts, classSymbol.Name);

			CodeBuilder codeBuilder = new();

			codeBuilder.AppendLine("// <auto-generated/>");
			codeBuilder.AppendLine();

			codeBuilder.AppendLine("#nullable enable");
			codeBuilder.AppendLine();

			using (codeBuilder.AddNamespace(classSymbol))
			{
				using (ClassBuilder classBuilder = codeBuilder.AddClass(classSymbol))
				{
					GenerateClass(tree.Root, codeBuilder, classBuilder);
				}
			}

			context.AddSource(classSymbol.Name, codeBuilder.ToString());
		}
	}

	private static void GenerateClass(Tree<string>.Node node, CodeBuilder codeBuilder, ClassBuilder classBuilder)
	{
		string id = node.Id;
		string className = (node.HasParent ? id + "Texts" : id).ToClassName();
		string baseClass = node.HasValue ? LocalizableReactiveProperty : "global::System.IDisposable";

		classBuilder.AddBase(baseClass);

		if (node.HasChildren)
		{
			codeBuilder.Field(LocalizationService, "_localizationService").Private().ReadOnly();
			codeBuilder.AppendLine();
		}

		CreateFields(node, codeBuilder);
		codeBuilder.AppendLine();

		CreateProperties(node, codeBuilder);
		codeBuilder.AppendLine();

		CreateConstructor(node, codeBuilder, className);
		codeBuilder.AppendLine();

		CreateDisposeMethod(node, codeBuilder);
		
		foreach (Tree<string>.Node child in node.Children)
		{
			if (!child.HasChildren)
			{
				continue;
			}

			codeBuilder.AppendLine();

			string childClassName = (child.HasParent ? child.Id + "Texts" : child.Id).ToClassName();
			using ClassBuilder childClassBuilder = codeBuilder.Class(childClassName);

			GenerateClass(child, codeBuilder, childClassBuilder);
		}
	}

	private static void CreateFields(Tree<string>.Node node, CodeBuilder codeBuilder)
	{
		foreach (Tree<string>.Node child in node.Children)
		{
			string childId = child.Id;
			string childClass = childId.ToPropertyName() + "Texts";

			if (child.HasChildren)
			{
				codeBuilder.Field($"{childClass}?", childId.ToFieldName()).Private();
				continue;
			}

			codeBuilder.Field($"{LocalizableReactiveProperty}?", childId.ToFieldName()).Private();
		}
	}

	private static void CreateProperties(Tree<string>.Node node, CodeBuilder codeBuilder)
	{
		foreach (Tree<string>.Node child in node.Children)
		{
			string childId = child.Id;
			string childClass = childId.ToPropertyName() + "Texts";

			string key = GetKey(child);
			string name = childId.ToPropertyName();
			string fieldName = childId.ToFieldName();

			if (child.HasChildren)
			{
				codeBuilder.AppendLine($"public {childClass} {name} => {fieldName} ?? ({fieldName} = new {childClass}(_localizationService));");
				continue;
			}

			string type = ReadOnlyReactiveProperty;
			string concreteType = LocalizableReactiveProperty;

			codeBuilder.AppendLine($"public {type} {name} => {fieldName} ?? ({fieldName} = new {concreteType}(_localizationService, @\"{key}\"));");
		}
	}

	private static void CreateConstructor(Tree<string>.Node node, CodeBuilder codeBuilder, string className)
	{
		codeBuilder.Append($"public {className}({LocalizationService} localizationService)");

		if (node.HasValue)
		{
			codeBuilder.Append($" : base(localizationService, \"{GetKey(node)}\")", indent: false);
		}

		codeBuilder.AppendLine();
		codeBuilder.AppendLine("{");
		codeBuilder.Indent();
		codeBuilder.AppendLine("_localizationService = localizationService;");
		codeBuilder.Unindent();
		codeBuilder.AppendLine("}");
	}

	private static void CreateDisposeMethod(Tree<string>.Node node, CodeBuilder codeBuilder)
	{
		string disposeOverride = node.HasValue ? "override " : "";

		using (codeBuilder.Method($"{disposeOverride}void", "Dispose").Public())
		{
			if (node.HasValue)
			{
				codeBuilder.AppendLine("base.Dispose();");
				codeBuilder.AppendLine();
			}

			foreach (Tree<string>.Node child in node.Children)
			{
				string childId = child.Id;

				if (!child.HasChildren)
				{
					codeBuilder.AppendLine($"{childId.ToFieldName()}?.Dispose();");
					continue;
				}

				codeBuilder.AppendLine($"{childId.ToFieldName()}?.Dispose();");
			}
		}
	}

	private static string GetKey(Tree<string>.Node node)
	{
		List<string> tokens = [];
		Tree<string>.Node? nodeIterator = node;

		while (nodeIterator != null)
		{
			tokens.Add(nodeIterator.Id);
			nodeIterator = nodeIterator.Parent;
		}

		// This is the name of the generated class.
		tokens.RemoveAt(tokens.Count - 1);
		tokens.Reverse();

		return string.Join(".", tokens);
	}

	private static Tree<string> BuildTree(List<LocalizedText> localizedTexts, string className)
	{
		Tree<string> tree = new(className);

		foreach (string id in localizedTexts.Select(x => x.Id).OrderBy(x => x.Length).Distinct())
		{
			string[] tokens = id.Split(['.'], StringSplitOptions.RemoveEmptyEntries);
			Tree<string>.Node node = tree.Root;

			for (int i = 0; i < tokens.Length; i++)
			{
				string token = tokens[i];
				Tree<string>.Node? matchedNode = node.Children.FirstOrDefault(x => x.Id == token);

				if (matchedNode == null)
				{
					bool hasValue = i == tokens.Length - 1;
					matchedNode = node.AddChild(token, hasValue);
				}

				node = matchedNode;
			}
		}

		return tree;
	}
}