// <auto-generated />
using Blastic.Wpf.Sample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blastic.Wpf.Sample.Migrations
{
	[DbContext(typeof(SampleContext))]
	[Migration("20200620112112_Initial")]
	partial class Initial
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.5");

			modelBuilder.Entity("Blastic.Wpf.Sample.Data.Customer", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("INTEGER");

				b.Property<string>("Address")
					.HasColumnType("TEXT");

				b.Property<string>("Name")
					.HasColumnType("TEXT");

				b.HasKey("Id");

				b.ToTable("Customers");
			});
#pragma warning restore 612, 618
		}
	}
}