<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DynamicData" />
		<PackageReference Include="System.Collections.Immutable" />
		<PackageReference Include="System.Reactive" />
	</ItemGroup>
</Project>
