<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
	<TargetFramework>net472</TargetFramework>
	<OutputType>WinExe</OutputType>
	<UseWPF>true</UseWPF>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<RootNamespace>Blastic.Sample</RootNamespace>
	<AssemblyName>Blastic.Sample</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
	<ProjectReference Include="..\Blastic\Blastic.csproj">
	  <Project>{2482d54f-3264-4dc1-9dbe-00cc325d39ef}</Project>
	  <Name>Blastic</Name>
	</ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Update="AppSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>